# Generated by Django 3.1.7 on 2021-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='key',
            field=models.TextField(default=1, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
