# Generated by Django 3.1.7 on 2021-08-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='key',
        ),
    ]
