# Generated by Django 3.1.7 on 2021-08-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
    ]
