# Generated by Django 3.1.7 on 2021-08-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210803_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type_product',
        ),
    ]
