# Generated by Django 3.1.7 on 2021-08-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_item_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Заказано')),
                ('count', models.IntegerField(default=0, verbose_name='Количество товаров')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Номер заказа',
                'verbose_name_plural': 'Номера заказов',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Order_numbers',
        ),
    ]
