# Generated by Django 3.1.7 on 2021-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210813_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default=1, max_length=150, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
